name: CI

on: [push, pull_request]

jobs:
  test_cpp:
    strategy:
      fail-fast: false
      matrix:
        target: [windows-x86, windows-x64, ubuntu, macos]
        include:
        - target: windows-x86
          vm: windows-latest
          hxcpp_flags: "-D HXCPP_M32"
        - target: windows-x64
          vm: windows-latest
          hxcpp_flags: "-D HXCPP_M64"
        - target: ubuntu
          vm: ubuntu-18.04
          hxcpp_flags: ""
        - target: macos
          vm: macos-latest
          hxcpp_flags: ""
    runs-on: ${{ matrix.vm }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true
      # Install dependencies
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - uses: actions/cache@v1
        id: cache-cobbletext
        with:
          path: cobbletext/
          key: cache-cobbletext-0.2.0-${{ matrix.target }}-v1
      - run: .github/workflows/get_cobbletext.sh ${{ matrix.target }} "0.2.0"
        if: steps.cache-cobbletext.outputs.cache-hit != 'true'
      - run: |
          haxelib install --quiet --always test.hxml
          haxelib install --quiet --always hxcpp
          haxelib git safety https://github.com/RealyUniqueName/Safety
      # Build and copy dependencies into test app directory
      - run: |
          haxe hxml/test.cpp.hxml \
            ${{ matrix.hxcpp_flags }} -D HXCPP_VERBOSE \
            -D COBBLES_UNIT_TEST \
            -D COBBLETEXT_INCLUDE_PATH=$GITHUB_WORKSPACE/cobbletext/include \
            -D COBBLETEXT_LIBRARIES_PATH=$GITHUB_WORKSPACE/cobbletext/lib
          cp -a cobbletext/lib/. ./out/cpp/
          if [ -d "cobbletext/bin/" ]; then cp -a cobbletext/bin/. ./out/cpp/; fi
      # Test
      - run: ./TestAll-debug
        working-directory: out/cpp
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/out/cpp
  test_hl_and_release:
    strategy:
      fail-fast: false
      matrix:
        # target: [windows-x86, windows-x64, ubuntu, macos]
        # shrug ¯\_(ツ)_/¯
        target: [windows-x64, ubuntu, macos]
        include:
        # - target: windows-x86
        #   vm: windows-latest
        - target: windows-x64
          vm: windows-latest
        - target: ubuntu
          vm: ubuntu-18.04
        - target: macos
          vm: macos-latest
    runs-on: ${{ matrix.vm }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true
      # Install dependencies
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - uses: microsoft/setup-msbuild@v1.0.0
        if: contains( matrix.target, 'windows' )
      - run: .github/workflows/get_hashlink_bin.sh ${{ matrix.target }} "1.11.0" "1.11"
        if: contains( matrix.target, 'windows' )
      - run: .github/workflows/get_hashlink.sh ${{ matrix.target }} "1.11"
        if: "! contains( matrix.target, 'windows' )"
      - uses: actions/cache@v1
        id: cache-cobbletext
        with:
          path: cobbletext/
          key: cache-cobbletext-0.2.0-${{ matrix.target }}-v1
      - run: .github/workflows/get_cobbletext.sh ${{ matrix.target }} "0.2.0"
        if: steps.cache-cobbletext.outputs.cache-hit != 'true'
      - run: |
          haxelib install --quiet --always test.hxml
          haxelib install --quiet --always hashlink
          haxelib git safety https://github.com/RealyUniqueName/Safety
      # Build and copy dependencies into app test directory
      - run: |
          haxe hxml/test.hl.hxml
          haxe hxml/test.hlc.hxml
      - run: |
          mkdir -p out/
          cd out/
          cmake .. -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_INCLUDE_PATH="$GITHUB_WORKSPACE/cobbletext/include;c:/hl/include" \
            -D CMAKE_LIBRARY_PATH="$GITHUB_WORKSPACE/cobbletext/lib;c:/hl/"
          cmake --build . --config Release
          cmake --install . --config Release --prefix install_dir/
      - run: |
          otool -L cobbles.hdll
          install_name_tool -change `otool -L cobbles.hdll | grep -E -o "@rpath/libcobbletext[^ ]+"` libcobbletext.dylib cobbles.hdll
          otool -L cobbles.hdll
        if: matrix.target == 'macos'
        working-directory: out/install_dir/lib/
      - run: |
          cp -a out/install_dir/lib/cobbles.hdll ./out/hl/
          cp -a out/install_dir/bin/. ./out/hl/
          cp -a cobbletext/lib/. ./out/hl/
          if [ -d "cobbletext/bin/" ]; then cp -a cobbletext/bin/. ./out/hl/; fi
      - run: |
          otool -L * || true
          otool -L /usr/local/bin/hl || true
        if: matrix.target == 'macos'
        working-directory: out/hl
      # Run test
      - run: $GITHUB_WORKSPACE/.github/workflows/run_test_hl.sh
        working-directory: out/hl
      - run: $GITHUB_WORKSPACE/.github/workflows/run_test_hlc.sh
        working-directory: out/hl
      # Package cobbles.hdll
      - uses: actions/upload-artifact@v2
        with:
          name: cobbles-${{ matrix.target }}-hdll
          path: out/install_dir/lib/cobbles.hdll
